//! large & old finder.
//!
//! surfaces files that are both big enough to matter and stale enough to
//! probably be forgotten. twin thresholds are the point: a 10 GB video
//! you edited yesterday isn't old, a 6 KB .gitignore from 2019 isn't
//! large. need both bars cleared.
//!
//! * [`pipeline`] pure parallel walker + filter + sort + truncate. takes
//!   an explicit now_secs so idle-age math is deterministic across hosts.
//! * [`stream`] wraps the pipeline in a bg thread with cancel + progress
//!   callback, mirrors 's stream layout.
//!
//! # staleness metric
//!
//! mtime only, not atime:
//!
//! * atime is unreliable. linux distros mount with relatime/noatime for
//!   SSD longevity, freezes atime at or near mtime. macOS sonoma+ disables
//!   atime on APFS. windows NTFS has had atime off by default since vista.
//!   building UI around that lies on half the user's disk.
//! * mtime captures "content hasn't changed" which matches the UX copy
//!   ("haven't touched in 6 months"). if user was *reading* the file,
//!   that's a real signal we miss, but under-surfacing beats over-surfacing.
//!
//! # dir skip list
//!
//! reuses [`super::dupes::IGNORED_DIR_NAMES`]. user wants "my old photo"
//! not "index.js in random node_modules mirror". build / pkg-manager
//! files are stale but regenerated by their tool, deleting them breaks
//! the owning project. directory-wise cleaning is what (junk) does.

pub mod pipeline;
pub mod stream;

use std::path::Path;
use std::time::{Instant, SystemTime, UNIX_EPOCH};

use serde::Serialize;

pub use pipeline::{find_large_old, FileSummary, FindError};
pub use stream::{
    next_large_old_handle_id, run_large_old_stream, LargeOldController, LargeOldEmit,
    LargeOldHandle, LargeOldInsert, LargeOldRegistry, ScanPhase,
};

/// default min file size. 50 MiB catches mid-sized VM disks, big Logic
/// sessions, forgotten videos. small enough Documents stays out.
pub const DEFAULT_MIN_BYTES: u64 = 50 * 1024 * 1024;

/// default idle threshold. 6 months = "forgot I still had this". shorter
/// surfaces too many in-flight files, longer misses last-quarter downloads.
pub const DEFAULT_MIN_DAYS_IDLE: u64 = 180;

/// max rows per scan. scatter plot renders ~1000 points without jank,
/// past that it smears and the table is faster to scroll.
pub const DEFAULT_MAX_RESULTS: usize = 1_000;

/// wire response. same shape emits as `large-old://progress` snapshots
/// and terminal `large-old://done`.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct LargeOldReport {
    pub root: String,
    pub files: Vec<FileSummary>,
    /// every regular file the walker matched (post min-bytes + min-days).
    /// files.len() < total_matched means list was truncated
    pub total_matched: u64,
    /// sum of bytes across matching files (untruncated)
    pub total_bytes: u64,
    /// total files stat'd. UI shows "scanned N files" so user knows walker
    /// isn't asleep
    pub total_files_scanned: u64,
    pub duration_ms: u64,
    pub phase: ScanPhase,
    pub min_bytes: u64,
    pub min_days_idle: u64,
}

/// sync entry point. UI uses [`stream`], this is for tests + one-shot callers
pub fn scan_large_old(
    root: &Path,
    min_bytes: u64,
    min_days_idle: u64,
    max_results: usize,
) -> Result<LargeOldReport, FindError> {
    let started = Instant::now();
    let now_secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let (files, total_matched, total_bytes, total_scanned) = find_large_old(
        root,
        min_bytes,
        min_days_idle,
        max_results,
        now_secs,
        None,
        None,
    )?;
    Ok(LargeOldReport {
        root: root.to_string_lossy().into_owned(),
        files,
        total_matched,
        total_bytes,
        total_files_scanned: total_scanned,
        duration_ms: started.elapsed().as_millis() as u64,
        phase: ScanPhase::Done,
        min_bytes,
        min_days_idle,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs::{self, File};
    use std::io::Write;
    use std::path::PathBuf;

    /// write file + backdate mtime to secs_ago before now
    fn write_aged(root: &Path, rel: &str, content: &[u8], secs_ago: u64) -> PathBuf {
        let full = root.join(rel);
        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        let mut f = File::create(&full).unwrap();
        f.write_all(content).unwrap();
        f.sync_all().unwrap();
        drop(f);
        let handle = File::options().write(true).open(&full).unwrap();
        let new_mtime = SystemTime::now() - std::time::Duration::from_secs(secs_ago);
        handle.set_modified(new_mtime).unwrap();
        full
    }

    #[test]
    fn surfaces_file_that_clears_both_thresholds() {
        let tmp = tempfile::tempdir().unwrap();
        write_aged(tmp.path(), "old_big.bin", &vec![7u8; 4096], 365 * 86400);
        let report = scan_large_old(tmp.path(), 1024, 30, 1000).unwrap();
        assert_eq!(report.files.len(), 1);
        assert_eq!(report.total_matched, 1);
        assert!(report.files[0].idle_days >= 360);
        assert!(report.files[0].bytes >= 4096);
    }

    #[test]
    fn drops_small_files_even_if_old() {
        let tmp = tempfile::tempdir().unwrap();
        write_aged(tmp.path(), "tiny_old.txt", b"hi", 365 * 86400);
        let report = scan_large_old(tmp.path(), 1024, 30, 1000).unwrap();
        assert!(report.files.is_empty());
        assert_eq!(report.total_matched, 0);
    }

    #[test]
    fn drops_fresh_files_even_if_large() {
        let tmp = tempfile::tempdir().unwrap();
        write_aged(tmp.path(), "big_new.bin", &vec![1u8; 4096], 60);
        let report = scan_large_old(tmp.path(), 1024, 30, 1000).unwrap();
        assert!(report.files.is_empty());
    }

    #[test]
    fn sorted_desc_by_bytes_tiebreak_by_path() {
        let tmp = tempfile::tempdir().unwrap();
        write_aged(tmp.path(), "small.bin", &vec![0u8; 2048], 365 * 86400);
        write_aged(tmp.path(), "huge.bin", &vec![0u8; 16_384], 365 * 86400);
        write_aged(tmp.path(), "mid.bin", &vec![0u8; 4096], 365 * 86400);
        let report = scan_large_old(tmp.path(), 1024, 30, 1000).unwrap();
        let paths: Vec<&str> = report.files.iter().map(|f| f.path.as_str()).collect();
        assert_eq!(paths.len(), 3);
        // huge > mid > small
        assert!(paths[0].contains("huge.bin"));
        assert!(paths[1].contains("mid.bin"));
        assert!(paths[2].contains("small.bin"));
    }

    #[test]
    fn truncates_rows_but_keeps_totals() {
        let tmp = tempfile::tempdir().unwrap();
        for i in 0..20 {
            write_aged(
                tmp.path(),
                &format!("f{i:02}.bin"),
                &vec![1u8; 4096 + i],
                365 * 86400,
            );
        }
        let report = scan_large_old(tmp.path(), 1024, 30, 5).unwrap();
        assert_eq!(report.files.len(), 5);
        assert_eq!(report.total_matched, 20);
        let summed_visible: u64 = report.files.iter().map(|f| f.bytes).sum();
        assert!(report.total_bytes > summed_visible);
    }

    #[test]
    fn symlinks_are_skipped() {
        #[cfg(unix)]
        {
            let tmp = tempfile::tempdir().unwrap();
            write_aged(tmp.path(), "real.bin", &vec![0u8; 4096], 365 * 86400);
            let link = tmp.path().join("alias.bin");
            std::os::unix::fs::symlink(tmp.path().join("real.bin"), &link).unwrap();
            let report = scan_large_old(tmp.path(), 1024, 30, 1000).unwrap();
            assert_eq!(report.files.len(), 1);
            assert!(report.files[0].path.ends_with("real.bin"));
        }
    }

    #[test]
    fn missing_root_returns_not_found() {
        let err =
            scan_large_old(Path::new("/definitely/not/here/safai-lo-xyz"), 0, 0, 1000).unwrap_err();
        assert!(matches!(err, FindError::NotFound(_)));
    }

    #[test]
    fn empty_directory_returns_empty_report() {
        let tmp = tempfile::tempdir().unwrap();
        let report = scan_large_old(tmp.path(), 1024, 30, 1000).unwrap();
        assert_eq!(report.files.len(), 0);
        assert_eq!(report.total_matched, 0);
        assert_eq!(report.total_bytes, 0);
    }

    #[test]
    fn skips_node_modules_subtree() {
        let tmp = tempfile::tempdir().unwrap();
        // 10 MiB inside node_modules, ancient but can't delete
        // individually without breaking the project. must not surface.
        write_aged(
            tmp.path(),
            "proj/node_modules/react/big.bin",
            &vec![0u8; 2 * 1024 * 1024],
            365 * 86400,
        );
        // and a real user file
        write_aged(
            tmp.path(),
            "Pictures/trip.bin",
            &vec![0u8; 4 * 1024 * 1024],
            365 * 86400,
        );
        let report = scan_large_old(tmp.path(), 1024, 30, 1000).unwrap();
        assert_eq!(report.files.len(), 1);
        assert!(report.files[0].path.contains("trip.bin"));
    }

    #[test]
    fn serializes_camelcase() {
        let tmp = tempfile::tempdir().unwrap();
        write_aged(tmp.path(), "a.bin", &vec![0u8; 4096], 365 * 86400);
        let report = scan_large_old(tmp.path(), 1024, 30, 1000).unwrap();
        let v = serde_json::to_value(&report).unwrap();
        assert!(v.get("totalMatched").is_some());
        assert!(v.get("totalBytes").is_some());
        assert!(v.get("totalFilesScanned").is_some());
        assert!(v.get("durationMs").is_some());
        assert!(v.get("minBytes").is_some());
        assert!(v.get("minDaysIdle").is_some());
        if let Some(f) = v["files"].as_array().and_then(|a| a.first()) {
            assert!(f.get("path").is_some());
            assert!(f.get("bytes").is_some());
            assert!(f.get("modified").is_some());
            assert!(f.get("idleDays").is_some());
            assert!(f.get("extension").is_some());
        }
    }

    #[test]
    fn idle_days_calculation_is_rounded_down() {
        // 2.5d aging -> idle_days = 2
        let tmp = tempfile::tempdir().unwrap();
        write_aged(tmp.path(), "a.bin", &vec![0u8; 4096], (2 * 86400) + 43_200);
        let report = scan_large_old(tmp.path(), 1024, 1, 1000).unwrap();
        assert_eq!(report.files.len(), 1);
        assert_eq!(report.files[0].idle_days, 2);
    }
}
