//! path/size -> event classification. pure functions, no filesystem IO or
//! clock calls outside deterministic params. own module so walker behaviour
//! can be pinned by table-driven tests.
//!
//! answers one question per entry: "should the live log show this, and if
//! so which badge?"
//!
//! does NOT decide deletability. deletion lives in the cleaner module, this
//! just drives UI chatter

use std::path::Path;

/// min size for a "found" event. below this is too common to merit a live
/// log line, rolls up into counters instead. 100 MiB keeps the log skimmable
/// during a home-dir scan
pub const FOUND_MIN_BYTES: u64 = 100 * 1024 * 1024;

/// path substrings that earn a "safe" badge. matched case-insensitively
/// against the full path. conservative, every phrase must name a directory
/// whose contents can be regenerated by the owning app without data loss.
///
/// seed, replaces with a platform-aware catalog in scanner::junk
pub const SAFE_MARKERS: &[&str] = &[
    // macOS + linux user caches
    "/library/caches/",
    "/.cache/",
    "/.npm/_cacache/",
    "/.pnpm-store/",
    "/.cargo/registry/cache/",
    "/go/pkg/mod/cache/",
    // xcode derived data, notoriously large, always regenerable
    "/library/developer/xcode/deriveddata/",
    // linux trash
    "/.local/share/trash/",
    // windows local temp + browser caches
    "\\appdata\\local\\temp\\",
    "\\appdata\\local\\google\\chrome\\user data\\default\\cache\\",
];

/// None from [`classify`] means "not interesting enough to log individually",
/// still contributes to aggregate counters
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    Found,
    Safe,
}

/// classify a single entry. `path` absolute, `size` bytes, `is_file`
/// discriminates regular files from dirs/symlinks. directories never produce
/// a verdict, dir-size roll-ups live in the treemap phase.
///
/// total: any input returns an answer
pub fn classify(path: &Path, size: u64, is_file: bool) -> Option<Verdict> {
    if !is_file {
        return None;
    }
    // SAFE wins over FOUND: a 2 GB entry inside ~/Library/Caches is more
    // usefully surfaced as "safe" (regenerable) than "found" (surprising)
    if is_safe_path(path) {
        return Some(Verdict::Safe);
    }
    if size >= FOUND_MIN_BYTES {
        return Some(Verdict::Found);
    }
    None
}

fn is_safe_path(path: &Path) -> bool {
    // markers are already lowercase
    let hay = path.to_string_lossy().to_ascii_lowercase();
    SAFE_MARKERS.iter().any(|m| hay.contains(m))
}

/// sample rate for scan-progress log lines. every Nth file emits a "scan"
/// event with its path so the live log shows motion without drowning IPC.
/// 500 gives ~1 line every few hundred ms during a home-dir walk
pub const SCAN_SAMPLE_EVERY: u64 = 500;

/// pure so walker sampling cadence is testable without a real walk
#[inline]
pub fn should_sample_scan(nth_file: u64) -> bool {
    nth_file > 0 && nth_file % SCAN_SAMPLE_EVERY == 0
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn p(s: &str) -> PathBuf {
        PathBuf::from(s)
    }

    #[test]
    fn directory_never_classifies() {
        assert_eq!(classify(&p("/any/path"), u64::MAX, false), None);
    }

    #[test]
    fn small_untagged_file_is_none() {
        assert_eq!(classify(&p("/home/u/doc.txt"), 4 * 1024, true), None);
    }

    #[test]
    fn large_file_is_found() {
        assert_eq!(
            classify(&p("/home/u/big.bin"), FOUND_MIN_BYTES, true),
            Some(Verdict::Found),
        );
        assert_eq!(
            classify(&p("/home/u/big.bin"), FOUND_MIN_BYTES + 1, true),
            Some(Verdict::Found),
        );
    }

    #[test]
    fn below_threshold_large_is_none() {
        assert_eq!(classify(&p("/x/y.bin"), FOUND_MIN_BYTES - 1, true), None);
    }

    #[test]
    fn cache_path_is_safe_at_any_size() {
        for p_str in &[
            "/Users/foo/Library/Caches/com.apple.Safari/webkit.db",
            "/home/foo/.cache/thumbnails/large/abc.png",
            "/home/foo/.npm/_cacache/content-v2/deadbeef",
            "/home/foo/.pnpm-store/v3/files/aa/bb",
            "/Users/foo/Library/Developer/Xcode/DerivedData/App-xyz/Build.log",
            "/home/foo/.cargo/registry/cache/index.crates.io-abc/tokio-1.0.crate",
        ] {
            assert_eq!(
                classify(&p(p_str), 8 * 1024, true),
                Some(Verdict::Safe),
                "expected Safe for {p_str}",
            );
        }
    }

    #[test]
    fn safe_wins_over_found_when_both_apply() {
        // 2 GB inside Caches -> Safe badge, not Found
        let path = p("/Users/foo/Library/Caches/Big/chunk.bin");
        assert_eq!(
            classify(&path, 2 * 1024 * 1024 * 1024, true),
            Some(Verdict::Safe),
        );
    }

    #[test]
    fn windows_style_temp_matches_case_insensitively() {
        // fs layers on windows frequently yield mixed-case paths
        let path = p(r"C:\Users\Foo\AppData\Local\Temp\installer.msi");
        assert_eq!(
            classify(&path, 500 * 1024 * 1024, true),
            Some(Verdict::Safe),
        );
    }

    #[test]
    fn unrelated_system_path_is_not_safe() {
        // don't overreach into locations where deletion would brick the
        // system. /Library/ (no Caches) must not match
        assert_eq!(
            classify(&p("/Library/LaunchDaemons/com.apple.x.plist"), 4096, true),
            None,
        );
        assert_eq!(classify(&p("/etc/hosts"), 4096, true), None,);
    }

    #[test]
    fn markers_are_non_empty_and_lowercase() {
        // case-insensitive match relies on markers being lc
        for m in SAFE_MARKERS {
            assert!(!m.is_empty());
            assert_eq!(*m, m.to_ascii_lowercase().as_str());
        }
    }

    #[test]
    fn scan_sampling_cadence() {
        assert!(!should_sample_scan(0));
        assert!(!should_sample_scan(1));
        assert!(!should_sample_scan(SCAN_SAMPLE_EVERY - 1));
        assert!(should_sample_scan(SCAN_SAMPLE_EVERY));
        assert!(should_sample_scan(SCAN_SAMPLE_EVERY * 2));
        assert!(!should_sample_scan(SCAN_SAMPLE_EVERY + 1));
    }
}
